<?php
/**
 * Plugin Name:       BTMC Gold Price
 * Plugin URI:        https://btmc.vn/
 * Description:       Hiển thị giá vàng BTMC theo thời gian thực thông qua shortcode.
 * Version:           1.0.0
 * Requires at least: 5.8
 * Requires PHP:      7.4
 * Author:            AutoGenerated Agent
 * License:           GPL-2.0-or-later
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       btmc-gold-price
 * Domain Path:       /languages
 */

defined( 'ABSPATH' ) || exit;

define( 'BTMC_GOLD_PRICE_PLUGIN_FILE', __FILE__ );
define( 'BTMC_GOLD_PRICE_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'BTMC_GOLD_PRICE_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

require_once BTMC_GOLD_PRICE_PLUGIN_DIR . 'includes/class-btmc-gold-price.php';

/**
 * Returns the main instance of the plugin.
 *
 * @return Btmc_Gold_Price
 */
function btmc_gold_price() {
    return Btmc_Gold_Price::instance();
}

btmc_gold_price();
